Repository PyvesB/advanced-achievements, pull requests merged in 2018-07, with the labels that each got.

#383 Update PAPI (closes #358)
  advanced-achievements-plugin/src/main/java/com/hm/achievement/lifecycle/PluginLoader.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/placeholder/AchievementPlaceholderHook.java
  pom.xml
Labels: developer-experience

#385 Add travis config and fix idea ignore
  .gitignore
  .travis.yml
  README.md
Labels: developer-experience

#379 Fixed Crafting Metadata Problem
  advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/statistics/CraftsListener.java
Labels: bug

#387 Advanced advancement customization: root advancement name and background.
  .travis.yml
  advanced-achievements-plugin/src/main/java/com/hm/achievement/advancement/AchievementAdvancement.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/advancement/AdvancementManager.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/config/FileUpdater.java
  advanced-achievements-plugin/src/main/resources/config.yml
Labels: enhancement

#400 config.yml and gui.yml for 1.13
  advanced-achievements-plugin/src/main/resources/config.yml
  advanced-achievements-plugin/src/main/resources/gui.yml
Labels: enhancement

#390 Implemented custom mob name support for Kills category (#360)
  advanced-achievements-plugin/src/main/java/com/hm/achievement/command/executable/ResetCommand.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/db/CacheManager.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/lifecycle/PluginLoader.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/statistics/KillsListener.java
  advanced-achievements-plugin/src/main/resources/config.yml
  advanced-achievements-plugin/src/main/resources/plugin.yml
Labels: enhancement
