Repository PyvesB/advanced-achievements, pull requests merged in 2020-04, with the labels that each got.

#690 Update lang-PL.yml
  advanced-achievements-plugin/src/main/resources/lang-PL.yml
Labels: translation

#706 Update lang-CN.yml
  advanced-achievements-plugin/src/main/resources/lang-CN.yml
Labels: translation

#710 Add support for selectors in AbstractParsableCommand
  advanced-achievements-plugin/src/main/java/com/hm/achievement/command/executable/AbstractParsableCommand.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/command/external/CommandUtils.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/command/external/LICENSE
  advanced-achievements-plugin/src/main/java/com/hm/achievement/lang/command/CmdLang.java
  advanced-achievements-plugin/src/main/resources/lang.yml
Labels: enhancement

#702 Issue 684
  advanced-achievements-plugin/src/main/java/com/hm/achievement/command/executable/ListCommand.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/lang/GuiLang.java
  advanced-achievements-plugin/src/main/resources/lang.yml
Labels: bug
