Repository PyvesB/advanced-achievements, pull requests merged in 2020-10, with the labels that each got.

#864 Add API to increase achievement values
  advanced-achievements-api/src/main/java/com/hm/achievement/api/AdvancedAchievementsAPI.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/api/AdvancedAchievementsBukkitAPI.java
  advanced-achievements-plugin/src/test/java/com/hm/achievement/api/AdvancedAchievementsBukkitAPINullSafetyTest.java
Labels: developer experience, enhancement

#867 Add files via upload
  advanced-achievements-plugin/src/main/resources/lang-SK.yml
Labels: translation

#874 Create JobsRebornListener
  advanced-achievements-api/src/main/java/com/hm/achievement/category/MultipleAchievements.java
  advanced-achievements-plugin/pom.xml
  advanced-achievements-plugin/src/main/java/com/hm/achievement/config/FileUpdater.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/statistics/JobsRebornListener.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/module/ReloadableModule.java
  advanced-achievements-plugin/src/main/resources/config.yml
  advanced-achievements-plugin/src/main/resources/gui-legacy.yml
  advanced-achievements-plugin/src/main/resources/gui.yml
  advanced-achievements-plugin/src/main/resources/lang.yml
  advanced-achievements-plugin/src/main/resources/plugin.yml
  pom.xml
Labels: enhancement
