Repository PyvesB/advanced-achievements, pull requests merged in 2020-02, with the labels that each got.

#656 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: dependencies

#658 Add Advancements Category
  advanced-achievements-api/src/main/java/com/hm/achievement/category/NormalAchievements.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/config/ConfigurationParser.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/config/FileUpdater.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/statistics/AdvancementsListener.java
  advanced-achievements-plugin/src/main/java/com/hm/achievement/module/ReloadableModule.java
  advanced-achievements-plugin/src/main/resources/config.yml
  advanced-achievements-plugin/src/main/resources/gui.yml
  advanced-achievements-plugin/src/main/resources/lang.yml
  advanced-achievements-plugin/src/main/resources/plugin.yml
Labels: enhancement

#661 Update Lang-ES.yml
  advanced-achievements-plugin/src/main/resources/lang-ES.yml
Labels: translation

#673 Updating lang-FR.yml with the last sentences from the last updates
  advanced-achievements-plugin/src/main/resources/lang-FR.yml
Labels: translation
